eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: feign-consumer

server:
  port: 9000
#  添加熔断配置，并开启
feign:
  hystrix:
    enabled: true